name: Train ML Model

on: [push]  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2

    - name: Set up Python  
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script  
      run: |
        python train.py

    - name: Print success message  
      run: echo "🎉 Model training completed successfully!"
